"""Protocol message names kept in one place to avoid spelling mistakes."""

JOIN = "join"
WELCOME = "welcome"
PLAYER_LIST = "player_list"
MATCH_START = "match_start"
ROUND_START = "round_start"
PATTERN_STEP = "pattern_step"
PATTERN_UPDATE = "pattern_update"
REPEAT_STEP = "repeat_step"
REPEAT_FEEDBACK = "repeat_feedback"
TIMER_UPDATE = "timer_update"
ROUND_RESULT = "round_result"
MATCH_RESULT = "match_result"
REMATCH_VOTE = "rematch_vote"
FORFEIT = "forfeit"
GAME_RESET = "game_reset"
PLAYER_LEFT = "player_left"
PING = "ping"
PONG = "pong"
ERROR = "error"

